color0 #1b2b36
color1 #fd4663
color2 #67c3e4
color3 #5c79d6
color4 #8266cc
color5 #93d4ec
color6 #96aae9
color7 #f2f3f3
color8 #5d6b71
color9 #fd4663
color10 #67c3e4
color11 #5c79d6
color12 #8266cc
color13 #93d4ec
color14 #96aae9
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #142029
background            #142029
foreground            #f2f3f3
selection_foreground  #afb4b6
selection_background  #1b2b36
active_border_color   #67c3e4
inactive_border_color #1b2b36
url_color             #67c3e4

active_tab_foreground   #182125
active_tab_background   #67c3e4
inactive_tab_foreground #afb4b6
inactive_tab_background #1b2b36
cursor_trail_color      #afb4b6
