color0 #212230
color1 #fd4663
color2 #8b8dc1
color3 #9781b1
color4 #ac84ae
color5 #acadd3
color6 #beafd0
color7 #f2f2f3
color8 #646575
color9 #fd4663
color10 #8b8dc1
color11 #9781b1
color12 #ac84ae
color13 #acadd3
color14 #beafd0
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #1a1a23
background            #1a1a23
foreground            #f2f2f3
selection_foreground  #afafb6
selection_background  #212230
active_border_color   #8b8dc1
inactive_border_color #212230
url_color             #8b8dc1

active_tab_foreground   #1b1b22
active_tab_background   #8b8dc1
inactive_tab_foreground #afafb6
inactive_tab_background #212230
cursor_trail_color      #afafb6
