color0 #082335
color1 #fd4663
color2 #65b2e7
color3 #4f5de3
color4 #98cc66
color5 #91c8ee
color6 #919aee
color7 #f2f2f3
color8 #606d75
color9 #fd4663
color10 #65b2e7
color11 #4f5de3
color12 #98cc66
color13 #91c8ee
color14 #919aee
color15 #f2f2f3

cursor                #f2f2f3
cursor_text_color     #082335
background            #082335
foreground            #f2f2f3
selection_foreground  #afb3b6
selection_background  #0b2e47
active_border_color   #65b2e7
inactive_border_color #0b2e47
url_color             #65b2e7
