"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[opener]
folder = [
  { run = '''fish -c "nvim "$1""''', block = true, desc = "neovim", for = "linux" },
  { run = 'kitty --detach nvim "$@"', orphan = true, desc = "neovim (detached)", for = "linux" },
  { run = '''fish -c "lazygit -p "$1""''', block = true, desc = "lazygit", for = "linux" },
  { run = 'kitty "$@"', orphan = true, desc = "kitty", for = "linux" },
]
text = [
  { run = '$EDITOR "$@"', block = true, desc = "$EDITOR", for = "linux" },
  { run = 'nvim "$@"', block = true, desc = "neovim", for = "linux" },
  { run = 'kitty --detach nvim "$@"', block = true, desc = "neovim (detached)", for = "linux" },
]
document = [
  { run = 'okular "$@"', orphan = true, desc = "libreoffice", for = "linux" },
  { run = 'libreoffice "$@"', orphan = true, desc = "libreoffice", for = "linux" },
]
image = [
  { run = '''fish -c "nvim "$1""''', block = true, desc = "neovim", for = "linux" },
  { run = 'kitty --detach nvim "$@"', orphan = true, desc = "neovim (detached)", for = "linux" },
  { run = 'gwenview "$@"', orphan = true, desc = "gwenview", for = "linux" },
]
video = [
  { run = 'haruna "$@"', orphan = true, desc = "mpv", for = "linux" },
  { run = 'mpv "$@"', orphan = true, desc = "mpv", for = "linux" },
  { run = 'vlc "$@"', orphan = true, desc = "vlc", for = "linux" },
]
audio = [
  { run = 'haruna "$@"', orphan = true, desc = "mpv", for = "linux" },
  { run = 'mpv "$@"', orphan = true, desc = "mpv", for = "linux" },
  { run = 'vlc "$@"', orphan = true, desc = "vlc", for = "linux" },
]
fallback = [
  { run = 'xdg-open "$@"', orphan = true, desc = "xdg-open", for = "linux" },
]


[open]
rules = [
  # folder
  { name = "*/", use = "folder" },

  # text
  { mime = "text/*", use = "text" },
  { mime = "inode/x-empty", use = "text" },
  { mime = "application/json", use = "text" },

  # document
  { mime = "application/pdf", use = "document" },
  { mime = "application/epub+zip", use = "document" },
  { mime = "application/x-mobipocket-ebook", use = "document" },

  # image
  { mime = "image/*", use = "image" },

  # video
  { mime = "application/octet-stream", use = "video" },

  # audio
  { mime = "audio/*", use = "audio" },

  # archive
  { mime = "application/zip", use = "archive" },
  { mime = "application/gzip", use = "archive" },
  { mime = "application/x-bzip", use = "archive" },
  { mime = "application/x-bzip2", use = "archive" },
  { mime = "application/x-tar", use = "archive" },
  { mime = "application/x-7z-compressed", use = "archive" },
  { mime = "application/x-rar", use = "archive" },

  # fallback
  { mime = "*", use = "fallback" },
]
