[audio]
enable_sounds = true

[backdrop]
enabled = true

[bar]
order = [ "vertical", "horizontal" ]

    [bar.horizontal]
    center = [ "clock", "media" ]
    enabled = false
    end = [ "clipboard", "network", "bluetooth", "brightness", "battery", "session" ]
    margin_edge = 0
    margin_ends = 0
    radius = 0
    start = [ "launcher", "workspaces" ]

        [bar.horizontal.monitor.HDMI-A-1]
        enabled = true

    [bar.vertical]
    background_opacity = 0.89999997615814209
    center = [ "weather", "spacer", "clock", "media" ]
    enabled = false
    end = [ "tray", "battery", "keyboard_layout", "volume" ]
    margin_edge = 3
    margin_ends = 240
    position = "left"
    radius = 18
    start = [ "notifications", "workspaces" ]

        [bar.vertical.monitor.DP-1]
        enabled = true

[brightness]
enable_ddcutil = true

[calendar]
enabled = true

    [calendar.account.orgmode]
    name = "OrgMode"
    provider = "custom"
    server_url = "http://localhost:5232/edpyt/org/"
    type = "caldav"
    username = "edpyt"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "mic_mute"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002" ]

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    cx = 204.09585571289062
    cy = 122.36164855957031
    output = "DP-1"
    rotation = 0.0
    scale = 1.3788429498672485
    type = "weather"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        background_opacity = 1.0
        color = "on_surface"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    cx = 990.933349609375
    cy = 956.0
    output = "DP-1"
    rotation = 0.0
    scale = 1.0666666030883789
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        background_color = "on_tertiary"
        background_opacity = 0.35000000000000003
        background_padding = 0.0
        background_radius = 27.0
        color = "on_surface"
        layout = "horizontal"
        shadow = true

[dock]
auto_hide = true
background_opacity = 0.89999997615814209
enabled = true
icon_size = 35
launcher_position = "start"
monitors = [ "DP-1" ]
pinned = [ "kitty", "zen" ]
show_dots = true

[location]
address = "Ufa, Russia"

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [
    "lockscreen-login-box@DP-1",
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 957.0
    output = "DP-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 0.0
    box_width = 0.0
    cx = 540.0
    cy = 1797.0
    output = "HDMI-A-1"
    rotation = 0.0
    type = "login_box"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 0.0
    box_width = 0.0
    cx = 1732.0
    cy = 92.0
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        color = "on_surface"
        format = "{:%H:%M}"
        shadow = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 961.0
    cy = 822.0
    output = "DP-1"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        background_color = "on_hover"
        background_opacity = 0.37
        background_padding = 10.0
        background_radius = 9.0
        color = "on_surface"
        layout = "horizontal"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 198.0
    cy = 98.5
    output = "DP-1"
    rotation = 0.0
    type = "weather"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 48.0
    box_width = 112.0
    cx = 1736.0
    cy = 134.5
    output = "DP-1"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        format = "{:%d.%m}"
        shadow = true

[nightlight]
force = true

[osd]
keyboard_layout = false
position = "bottom_center"

[shell]
avatar_path = "/home/edpyt/Downloads/tadc-bubble.gif"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = false

    [shell.mpris]
    blacklist = [ "mpv" ]

    [shell.panel]
    launcher_categories = false
    session_placement = "centered"
    transparency_mode = "soft"
    wallpaper_placement = "centered"

    [[shell.session.actions]]
    action = "command"
    command = "noctalia msg session lock-and-suspend"
    enabled = true
    glyph = "suspend"
    label = "Sleep"
    shortcut = "s"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    enabled = true
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    enabled = true
    shortcut = "r"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    enabled = true
    shortcut = "q"
    variant = "secondary"

[theme]
builtin = "Rosé Pine"
community_palette = "Rose Pine Moon"
custom_palette = "ADW"
mode = "dark"
source = "community"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "gtk3", "gtk4", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "tauon", "zen-browser", "neovim", "discord", "papirus-icons" ]

[wallpaper]
directory = "/home/edpyt/wallpapers"

    [wallpaper.default]
    path = "/home/edpyt/wallpapers/wallhaven-k875o6_1920x1080.png"

    [wallpaper.last]
    path = "/home/edpyt/wallpapers/wallhaven-w5m326_1920x1080.png"

    [wallpaper.monitors.DP-1]
    path = "/home/edpyt/wallpapers/wallhaven-w5m326_1920x1080.png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/edpyt/wallpapers/wallhaven-yqv7xg_1080x1920.png"

    [[wallpaper.favorite]]
    community_palette = "Catppuccin Lavender"
    palette_source = "community"
    path = "/home/edpyt/wallpapers/wallhaven-e8ed5w_1920x1080.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    community_palette = "Catppuccin Lavender"
    palette_source = "community"
    path = "/home/edpyt/wallpapers/wallhaven-k875o6_1920x1080.png"
    theme_mode = "dark"

[widget.clock]
vertical_format = "{:%H\\n%M\\n-\\n%d\\n%m}"

[widget.keyboard_layout]
display = "short"
hide_label = false

[widget.media]
capsule = false

[widget.spacer]
capsule = false

[widget.volume]
capsule = false
device = "output"
show_label = true

[widget.workspaces]
capsule = false
display = "none"
hide_when_empty = false