config_version = 14

[audio]
enable_overdrive = true
enable_sounds = true

[backdrop]
enabled = true

[bar]
order = [ "vertical", "horizontal" ]

    [bar.horizontal]
    center = [ "mpvpaper_2", "clock", "recorder" ]
    enabled = false
    end = [ "clipboard", "network", "bluetooth", "brightness", "battery", "session" ]
    margin_edge = 0
    margin_ends = 0
    position = "bottom"
    radius = 0
    start = [ "launcher", "workspaces", "wallhaven" ]

        [bar.horizontal.monitor.HDMI-A-1]
        enabled = true

    [bar.vertical]
    border = "surface_variant"
    border_width = 1.0
    center = [ "weather", "spacer", "clock", "media" ]
    enabled = false
    end = [ "tray", "battery", "keyboard_layout", "volume" ]
    hover_highlight = false
    margin_ends = 220
    position = "left"
    radius_bottom_left = 0
    radius_top_left = 0
    shadow = false
    start = [ "notifications", "workspaces" ]

        [bar.vertical.dead_zone.actions]
        scroll_down = "workspace-switch next"
        scroll_up = "workspace-switch prev"

        [bar.vertical.monitor.DP-1]
        enabled = true

[brightness]
enable_ddcutil = true

[calendar]
enabled = true
refresh_minutes = 5

    [calendar.account.orgmode]
    calendars = [ "org" ]
    name = "OrgMode"
    provider = "custom"
    server_url = "http://localhost:5232/edpyt/org/"
    type = "caldav"
    username = "edpyt"

[[control_center.shortcuts]]
type = "bluetooth"

[[control_center.shortcuts]]
type = "notification"

[[control_center.shortcuts]]
type = "power_profile"

[[control_center.shortcuts]]
type = "mic_mute"

[[control_center.shortcuts]]
type = "caffeine"

[desktop_widgets]
schema_version = 1
widget_order = [ "desktop-widget-0000000000000007", "desktop-widget-0000000000000004", "desktop-widget-0000000000000006" ]

    [desktop_widgets.grid]
    cell_size = 64
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000004]
    box_height = 128.0
    box_width = 320.0
    cx = 508.0
    cy = 1664.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "media_player"

        [desktop_widgets.widget.desktop-widget-0000000000000004.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        color = "on_surface"
        font_family = ""
        hide_when_no_media = true
        layout = "horizontal"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000006]
    box_height = 448.0
    box_width = 640.0
    cx = 540.0
    cy = 960.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "calendar"

        [desktop_widgets.widget.desktop-widget-0000000000000006.settings]
        background = true
        background_color = "surface"
        background_opacity = 0.80000000000000004
        background_padding = 10
        background_radius = 12
        font_family = ""
        show_events = true
        show_week_numbers = true

    [desktop_widgets.widget.desktop-widget-0000000000000007]
    box_height = 64.0
    box_width = 320.0
    cx = 508.0
    cy = 1568.0
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000007.settings]
        background = false
        bands = 12
        centered = false
        mirrored = true
        show_when_idle = false

[dock]
auto_hide = true
background_opacity = 0.99999997764825821
enabled = true
icon_size = 35
launcher_position = "start"
monitors = [ "DP-1" ]
pinned = [ "kitty", "zen" ]
reserve_space = false
show_dots = true

[hot_corners]
enabled = true

    [hot_corners.bottom_right]
    action = "launcher"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 1200.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = false
    timeout = 660.0

[location]
address = "Ufa, Russia"

[lockscreen]
blur_intensity = 0.0
fingerprint = false

[lockscreen_widgets]
enabled = true
schema_version = 1
widget_order = [ "lockscreen-login-box@DP-1", "lockscreen-login-box@HDMI-A-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 976.0
    cy = 809.5
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-1".settings]
        center_password_text = false
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 524.0
    cy = 1645.5
    enabled = false
    output = "HDMI-A-1"
    placement_height = 1920.0
    placement_width = 1080.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 304.0
    box_width = 608.0
    cx = 1008.0
    cy = 516.0
    output = "DP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = false

[nightlight]
force = true

[osd]
keyboard_layout = false
position = "bottom_center"

    [osd.kinds]
    keyboard_layout = false
    media = false

[plugin_settings."noctalia/kaomoji"]
notify_on_copy = false

[plugin_settings."noctalia/mpvpaper"]
auto_pause = "off"
picker_placement = "floating"
picker_position = "center"
video_directory = "~/wallpapers/"

[plugin_settings."noctalia/screen_recorder"]
directory = ""

[plugin_settings."noctalia/translator"]
target_lang = "en"

[plugin_settings."noctalia/wallhaven"]
browser_placement = "floating"
browser_position = "center"
download_dir = "~/wallpapers/"

[plugin_settings."noctalia/wallpaper_depth"]
auto_generate = false
manager_placement = "floating"
manager_position = "center"

[plugin_settings."umedbazarov/ruh-vpn"]
backend_python = "~/.local/share/ruh-vpn-venv/bin/python3"
vpn_panel_placement = "floating"
vpn_panel_position = "center"

[plugin_settings."yuuto/arch-updater"]
aur_helper = "paru"
check_arch_news = false
notify_on_updates = false
panel_placement = "floating"
panel_position = "center"

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/wallhaven", "noctalia/kaomoji", "noctalia/translator" ]

[shell]
avatar_path = "/home/edpyt/Downloads/dragon-ball-z-dbz-crystal-ball-2-stars-png-701751694862287amivyupcfd-2823434995.png"
niri_overview_type_to_launch_enabled = true
password_style = "random"
polkit_agent = true
screen_time_enabled = true
settings_show_advanced = true
telemetry_enabled = false

    [shell.animation]
    enabled = false

    [shell.launcher]
    pinned = [ "zen", "emacsclient", "org.keepassxc.KeePassXC", "Happ" ]

    [shell.mpris]
    blacklist = [ "mpv", "Blanket" ]

    [shell.panel]
    control_center_position = "center"
    launcher_categories = false
    session_placement = "floating"
    session_position = "center"
    wallpaper_placement = "floating"
    wallpaper_position = "center"

    [[shell.session.actions]]
    action = "command"
    command = "noctalia msg session lock-and-suspend"
    countdown_seconds = 0.0
    enabled = true
    glyph = "suspend"
    label = "Спать"
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "secondary"

[system.monitor]
gpu_poll_seconds = 5

[theme]
builtin = "Eldritch"
community_palette = "Everforest Alt"
custom_palette = "wallhaven-8gg1do-vib"
mode = "dark"
source = "community"
wallpaper_scheme = "dysfunctional"

    [theme.templates]
    builtin_ids = [ "btop", "cava", "emacs", "gtk3", "gtk4", "kcolorscheme", "kitty", "niri", "qt" ]
    community_ids = [ "zen-browser", "discord", "heroiclauncher", "prismlauncher", "steam", "fastfetch", "zellij", "papirus-icons" ]

[wallpaper]
directory = "/home/edpyt/wallpapers"

    [wallpaper.default]
    path = "/home/edpyt/wallpapers/wallhaven-w5x99p.jpg"

    [wallpaper.last]
    path = "/home/edpyt/wallpapers/wallhaven-w5x99p.jpg"

    [wallpaper.monitors.DP-1]
    path = "/home/edpyt/wallpapers/wallhaven-w5x99p.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/edpyt/wallpapers/wallhaven-w5x99p.jpg"

    [[wallpaper.favorite]]
    community_palette = "Everforest Alt"
    palette_source = "community"
    path = "/home/edpyt/wallpapers/wallhaven-w5x99p.jpg"
    theme_mode = "dark"

[widget.audio_visualizer]
mirrored = false

[widget.cat]
audio_spectrum = true
rave_mode = true
tappy_mode = true
type = "noctalia/bongocat:cat"

[widget.clock]
vertical_format = "{:\\n%H\\n%M\\n-\\n%d\\n%m}"

[widget.keyboard_layout]
display = "short"
hide_label = false

[widget.media]
capsule = false
hide_when_no_media = true
show_progress = true
title_scroll = "always"

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.mpvpaper_2]
type = "noctalia/mpvpaper:mpvpaper"

[widget.notifications]
hide_when_no_unread = true

[widget.recorder]
type = "noctalia/screen_recorder:recorder"

[widget.volume]
capsule = false
color = "primary"
device = "output"
show_label = true

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
empty_color = "on_surface"
focused_output_only = true
hide_when_empty = false
occupied_color = "on_surface_variant"
style = "minimal"