[shell]
lang = "ru"

[theme.templates.user.nvim]
input_path  = "./templates/neovim.lua"
output_path = "~/.config/nvim/lua/functions/matugen.lua"
post_hook = "pkill -SIGUSR1 nvim"

[theme.templates.user.subtui]
input_path  = "~/.config/subtui/subtui-template.toml"
output_path = "~/.config/subtui/config.toml"
post_hook = "pkill -SIGUSR1 subtui"
