[shell]
lang = "ru"

[theme.templates.user.subtui]
input_path  = "~/.config/subtui/subtui-template.toml"
output_path = "~/.config/subtui/config.toml"
post_hook = "pkill -SIGUSR1 subtui"

[brightness.monitor.DP-1]
backend = "ddcutil"

[brightness.monitor.HDMI-A-1]
backend = "ddcutil"

[osd]
keyboard_layout = true
